export const STORE_THE_FEEDBACK="STORE_THE_FEEDBACK";
export const GETTING_THE_FEEDBACKS="GETTING_THE_FEEDBACKS";
export const AUTH_START="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";
export const LOG_OUT="LOG_OUT";
export const CLEAR_THE_DATA="CLEAR_THE_DATA";
export const CHANGE_THE_LOGIN_STATE="CHANGE_THE_LOGIN_STATE";